INSERT INTO category(description) VALUES ('Americain')
INSERT INTO category(description) VALUES ('Italien')
INSERT INTO category(description) VALUES ('Mexican')
INSERT INTO category(description) VALUES ('Fast Food')
INSERT INTO unit_of_measure(uom) VALUES ('Clove')
INSERT INTO unit_of_measure(uom) VALUES ('Each')

INSERT INTO unit_of_measure(uom) VALUES ('dash')
INSERT INTO unit_of_measure(uom) VALUES ('Ripe')
INSERT INTO unit_of_measure(uom) VALUES ('Teaspoon')
INSERT INTO unit_of_measure(uom) VALUES ('TableSpoon')
INSERT INTO unit_of_measure(uom) VALUES ('Cup')
INSERT INTO unit_of_measure(uom) VALUES ('Pinch')
INSERT INTO unit_of_measure(uom) VALUES ('Ounce')
